window.APP_DATA = {
  updatedAt: '2026-06-15T01:10:00-05:00',
  competition: {
    name: 'Copa del Mundo 2026',
    season: '2026',
    country: 'Mundial',
  },
  sports: ['Fútbol', 'Baloncesto', 'Tenis', 'Béisbol', 'Vóley'],
  leagues: [
    'Copa del Mundo 2026',
    'Mundial de Clubes',
    'Copa América',
    'Eurocopa',
    'Liga 1 Perú',
  ],
  teams: [
    'Argentina',
    'Brasil',
    'México',
    'Canadá',
    'España',
    'Francia',
    'Inglaterra',
    'Portugal',
    'Alemania',
    'Colombia',
    'Uruguay',
    'Japón',
    'Marruecos',
    'Estados Unidos',
    'Bélgica',
    'Croacia',
  ],
  fixtures: [
    {
      id: 'esp-cpv',
      dateLabel: 'Hoy, 15 jun',
      status: 'upcoming',
      time: '14:00',
      group: 'Grupo A',
      home: { name: 'España', code: 'ESP', flag: '🇪🇸', score: null },
      away: { name: 'Cabo Verde', code: 'CPV', flag: '🇨🇻', score: null },
    },
    {
      id: 'bel-egy',
      dateLabel: 'Hoy, 15 jun',
      status: 'live',
      minute: 68,
      time: 'En vivo',
      group: 'Grupo A',
      home: { name: 'Bélgica', code: 'BEL', flag: '🇧🇪', score: 1 },
      away: { name: 'Egipto', code: 'EGY', flag: '🇪🇬', score: 0 },
    },
    {
      id: 'ksa-uru',
      dateLabel: 'Mañana, 16 jun',
      status: 'upcoming',
      time: '13:00',
      group: 'Grupo B',
      home: { name: 'Arabia Saudita', code: 'KSA', flag: '🇸🇦', score: null },
      away: { name: 'Uruguay', code: 'URU', flag: '🇺🇾', score: null },
    },
    {
      id: 'irn-nzl',
      dateLabel: 'Mañana, 16 jun',
      status: 'upcoming',
      time: '16:00',
      group: 'Grupo B',
      home: { name: 'Irán', code: 'IRN', flag: '🇮🇷', score: null },
      away: { name: 'Nueva Zelanda', code: 'NZL', flag: '🇳🇿', score: null },
    },
    {
      id: 'fra-sen',
      dateLabel: 'Mañana, 16 jun',
      status: 'upcoming',
      time: '19:00',
      group: 'Grupo C',
      home: { name: 'Francia', code: 'FRA', flag: '🇫🇷', score: null },
      away: { name: 'Senegal', code: 'SEN', flag: '🇸🇳', score: null },
    },
    {
      id: 'arg-alg',
      dateLabel: '17 jun',
      status: 'upcoming',
      time: '20:00',
      group: 'Grupo D',
      home: { name: 'Argentina', code: 'ARG', flag: '🇦🇷', score: null },
      away: { name: 'Argelia', code: 'ALG', flag: '🇩🇿', score: null },
    },
  ],
  standings: [
    {
      group: 'Grupo A',
      rows: [
        { team: 'Bélgica', flag: '🇧🇪', pj: 1, g: 1, e: 0, p: 0, gf: 1, gc: 0, pts: 3 },
        { team: 'España', flag: '🇪🇸', pj: 0, g: 0, e: 0, p: 0, gf: 0, gc: 0, pts: 0 },
        { team: 'Cabo Verde', flag: '🇨🇻', pj: 0, g: 0, e: 0, p: 0, gf: 0, gc: 0, pts: 0 },
        { team: 'Egipto', flag: '🇪🇬', pj: 1, g: 0, e: 0, p: 1, gf: 0, gc: 1, pts: 0 },
      ],
    },
    {
      group: 'Grupo B',
      rows: [
        { team: 'Uruguay', flag: '🇺🇾', pj: 0, g: 0, e: 0, p: 0, gf: 0, gc: 0, pts: 0 },
        { team: 'Arabia Saudita', flag: '🇸🇦', pj: 0, g: 0, e: 0, p: 0, gf: 0, gc: 0, pts: 0 },
        { team: 'Irán', flag: '🇮🇷', pj: 0, g: 0, e: 0, p: 0, gf: 0, gc: 0, pts: 0 },
        { team: 'Nueva Zelanda', flag: '🇳🇿', pj: 0, g: 0, e: 0, p: 0, gf: 0, gc: 0, pts: 0 },
      ],
    },
  ],
  news: [
    {
      tag: 'Fixture',
      title: 'El calendario del Mundial 2026 ya está cargado',
      summary: 'Consulta partidos por fecha, estado y marcador. Los datos reales se actualizan desde la API conectada.',
    },
    {
      tag: 'Clasificación',
      title: 'Tabla de posiciones por grupos',
      summary: 'Sigue puntos, goles y partidos jugados de cada selección durante la fase de grupos.',
    },
    {
      tag: 'En vivo',
      title: 'Marcadores en tiempo real desde football-data',
      summary: 'La web usa un proxy local para mostrar resultados reales cuando el proveedor entrega datos del torneo.',
    },
  ],
};
